name: PHP Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none

    - name: PHP Lint
      run: find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 -P4 php -l
